from flask import Flask, render_template, request
from datetime import datetime
import pytz

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route("/p2")
def page2():
    now = datetime.now()
    current_time = now.strftime("%Y-%m-%d %H:%M:%S")
    my_name = "Rafin"
    return render_template('page2.html', this_guy=my_name, current_time=current_time)

@app.route("/bio")
def bio():
    return render_template('bio.html')

@app.route('/world-clock', methods=['GET', 'POST'])
def world_clock():
    available_cities = {
        # North America
        'New York': 'America/New_York',
        'Los Angeles': 'America/Los_Angeles',
        'Chicago': 'America/Chicago',
        'Toronto': 'America/Toronto',
        'Vancouver': 'America/Vancouver',
        'Montreal': 'America/Montreal',
        'Mexico City': 'America/Mexico_City',
        'Guadalajara': 'America/Mexico_City',
        'Phoenix': 'America/Phoenix',
        'Denver': 'America/Denver',
        'Atlanta': 'America/New_York',
        'Miami': 'America/New_York',
        'Seattle': 'America/Los_Angeles',
        'San Francisco': 'America/Los_Angeles',
        'Las Vegas': 'America/Los_Angeles',
        'Anchorage': 'America/Anchorage',
        'Honolulu': 'Pacific/Honolulu',
        'Boston': 'America/New_York',
        'Washington DC': 'America/New_York',
        'Philadelphia': 'America/New_York',
        'Detroit': 'America/Detroit',
        'Houston': 'America/Chicago',
        'Dallas': 'America/Chicago',
        'San Antonio': 'America/Chicago',
        'Austin': 'America/Chicago',
        'Fort Worth': 'America/Chicago',
        'Columbus': 'America/New_York',
        'Charlotte': 'America/New_York',
        'San Diego': 'America/Los_Angeles',
        'Indianapolis': 'America/Indiana/Indianapolis',
        'Jacksonville': 'America/New_York',
        'Nashville': 'America/Chicago',
        'Oklahoma City': 'America/Chicago',
        'Portland': 'America/Los_Angeles',
        'Memphis': 'America/Chicago',
        'Louisville': 'America/New_York',
        'Baltimore': 'America/New_York',
        'Milwaukee': 'America/Chicago',
        'Albuquerque': 'America/Denver',
        'Tucson': 'America/Phoenix',
        'Fresno': 'America/Los_Angeles',
        'Sacramento': 'America/Los_Angeles',
        'Kansas City': 'America/Chicago',
        'Mesa': 'America/Phoenix',
        'Virginia Beach': 'America/New_York',
        'Colorado Springs': 'America/Denver',
        'Omaha': 'America/Chicago',
        'Raleigh': 'America/New_York',
        'Long Beach': 'America/Los_Angeles',
        'Miami Beach': 'America/New_York',
        'Tampa': 'America/New_York',
        'New Orleans': 'America/Chicago',
        'Cleveland': 'America/New_York',
        'Wichita': 'America/Chicago',
        'Arlington': 'America/Chicago',
        'Bakersfield': 'America/Los_Angeles',
        'Aurora': 'America/Denver',
        'Anaheim': 'America/Los_Angeles',
        'Santa Ana': 'America/Los_Angeles',
        'St. Louis': 'America/Chicago',
        'Riverside': 'America/Los_Angeles',
        'Corpus Christi': 'America/Chicago',
        'Lexington': 'America/New_York',
        'Pittsburgh': 'America/New_York',
        'Stockton': 'America/Los_Angeles',
        'Cincinnati': 'America/New_York',
        'St. Paul': 'America/Chicago',
        'Toledo': 'America/New_York',
        'Newark': 'America/New_York',
        'Greensboro': 'America/New_York',
        'Plano': 'America/Chicago',
        'Henderson': 'America/Los_Angeles',
        'Lincoln': 'America/Chicago',
        'Buffalo': 'America/New_York',
        'Jersey City': 'America/New_York',
        'Chula Vista': 'America/Los_Angeles',
        'Fort Wayne': 'America/Indiana/Indianapolis',
        'Orlando': 'America/New_York',
        'St. Petersburg': 'America/New_York',
        'Chandler': 'America/Phoenix',
        'Laredo': 'America/Chicago',
        'Norfolk': 'America/New_York',
        'Durham': 'America/New_York',
        'Madison': 'America/Chicago',
        'Lubbock': 'America/Chicago',
        'Irvine': 'America/Los_Angeles',
        'Winston-Salem': 'America/New_York',
        'Glendale': 'America/Phoenix',
        'Garland': 'America/Chicago',
        'Hialeah': 'America/New_York',
        'Reno': 'America/Los_Angeles',
        'Chesapeake': 'America/New_York',
        'Gilbert': 'America/Phoenix',
        'Baton Rouge': 'America/Chicago',
        'Irving': 'America/Chicago',
        'Scottsdale': 'America/Phoenix',
        'North Las Vegas': 'America/Los_Angeles',
        'Fremont': 'America/Los_Angeles',
        'Boise': 'America/Boise',
        'Richmond': 'America/New_York',
        'San Bernardino': 'America/Los_Angeles',
        'Birmingham': 'America/Chicago',
        'Spokane': 'America/Los_Angeles',
        'Rochester': 'America/New_York',
        'Des Moines': 'America/Chicago',
        'Modesto': 'America/Los_Angeles',
        'Fayetteville': 'America/New_York',
        'Tacoma': 'America/Los_Angeles',
        'Oxnard': 'America/Los_Angeles',
        'Fontana': 'America/Los_Angeles',
        'Columbus': 'America/New_York',
        'Montgomery': 'America/Chicago',
        'Moreno Valley': 'America/Los_Angeles',
        'Shreveport': 'America/Chicago',
        'Aurora': 'America/Chicago',
        'Yonkers': 'America/New_York',
        'Akron': 'America/New_York',
        'Huntington Beach': 'America/Los_Angeles',
        'Little Rock': 'America/Chicago',
        'Augusta': 'America/New_York',
        'Amarillo': 'America/Chicago',
        'Glendale': 'America/Los_Angeles',
        'Mobile': 'America/Chicago',
        'Grand Rapids': 'America/New_York',
        'Salt Lake City': 'America/Denver',
        'Tallahassee': 'America/New_York',
        'Huntsville': 'America/Chicago',
        'Grand Prairie': 'America/Chicago',
        'Knoxville': 'America/New_York',
        'Worcester': 'America/New_York',
        'Newport News': 'America/New_York',
        'Brownsville': 'America/Chicago',
        'Overland Park': 'America/Chicago',
        'Santa Clarita': 'America/Los_Angeles',
        'Providence': 'America/New_York',
        'Garden Grove': 'America/Los_Angeles',
        'Chattanooga': 'America/New_York',
        'Oceanside': 'America/Los_Angeles',
        'Jackson': 'America/Chicago',
        'Fort Lauderdale': 'America/New_York',
        'Santa Rosa': 'America/Los_Angeles',
        'Rancho Cucamonga': 'America/Los_Angeles',
        'Port St. Lucie': 'America/New_York',
        'Tempe': 'America/Phoenix',
        'Ontario': 'America/Los_Angeles',
        'Vancouver WA': 'America/Los_Angeles',
        'Cape Coral': 'America/New_York',
        'Sioux Falls': 'America/Chicago',
        'Springfield': 'America/Chicago',
        'Peoria': 'America/Chicago',
        'Pembroke Pines': 'America/New_York',
        'Elk Grove': 'America/Los_Angeles',
        'Salem': 'America/Los_Angeles',
        'Lancaster': 'America/Los_Angeles',
        'Corona': 'America/Los_Angeles',
        'Eugene': 'America/Los_Angeles',
        'Palmdale': 'America/Los_Angeles',
        'Salinas': 'America/Los_Angeles',
        'Springfield': 'America/New_York',
        'Pasadena': 'America/Los_Angeles',
        'Fort Collins': 'America/Denver',
        'Hayward': 'America/Los_Angeles',
        'Pomona': 'America/Los_Angeles',
        'Cary': 'America/New_York',
        'Rockford': 'America/Chicago',
        'Alexandria': 'America/New_York',
        'Escondido': 'America/Los_Angeles',
        'McKinney': 'America/Chicago',
        'Kansas City KS': 'America/Chicago',
        'Joliet': 'America/Chicago',
        'Sunnyvale': 'America/Los_Angeles',
        'Torrance': 'America/Los_Angeles',
        'Bridgeport': 'America/New_York',
        'Lakewood': 'America/Denver',
        'Hollywood': 'America/New_York',
        'Paterson': 'America/New_York',
        'Naperville': 'America/Chicago',
        'Syracuse': 'America/New_York',
        'Mesquite': 'America/Chicago',
        'Dayton': 'America/New_York',
        'Savannah': 'America/New_York',
        'Clarksville': 'America/Chicago',
        'Orange': 'America/Los_Angeles',
        'Pasadena': 'America/Chicago',
        'Fullerton': 'America/Los_Angeles',
        'Killeen': 'America/Chicago',
        'Frisco': 'America/Chicago',
        'Hampton': 'America/New_York',
        'McAllen': 'America/Chicago',
        'Warren': 'America/New_York',
        'Bellevue': 'America/Los_Angeles',
        'West Valley City': 'America/Denver',
        'Columbia': 'America/New_York',
        'Olathe': 'America/Chicago',
        'Sterling Heights': 'America/New_York',
        'New Haven': 'America/New_York',
        'Miramar': 'America/New_York',
        'Waco': 'America/Chicago',
        'Thousand Oaks': 'America/Los_Angeles',
        'Cedar Rapids': 'America/Chicago',
        'Charleston': 'America/New_York',
        'Visalia': 'America/Los_Angeles',
        'Topeka': 'America/Chicago',
        'Elizabeth': 'America/New_York',
        'Gainesville': 'America/New_York',
        'Thornton': 'America/Denver',
        'Roseville': 'America/Los_Angeles',
        'Carrollton': 'America/Chicago',
        'Coral Springs': 'America/New_York',
        'Stamford': 'America/New_York',
        'Simi Valley': 'America/Los_Angeles',
        'Concord': 'America/Los_Angeles',
        'Hartford': 'America/New_York',
        'Kent': 'America/Los_Angeles',
        'Lafayette': 'America/Chicago',
        'Midland': 'America/Chicago',
        'Surprise': 'America/Phoenix',
        'Denton': 'America/Chicago',
        'Victorville': 'America/Los_Angeles',
        'Evansville': 'America/Chicago',
        'Santa Clara': 'America/Los_Angeles',
        'Abilene': 'America/Chicago',
        'Athens': 'America/New_York',
        'Vallejo': 'America/Los_Angeles',
        'Allentown': 'America/New_York',
        'Norman': 'America/Chicago',
        'Beaumont': 'America/Chicago',
        'Independence': 'America/Chicago',
        'Murfreesboro': 'America/Chicago',
        'Ann Arbor': 'America/New_York',
        'Fargo': 'America/Chicago',
        'Wilmington': 'America/New_York',
        'Golden': 'America/Denver',
        'Columbia': 'America/Chicago',
        'Pearland': 'America/Chicago',
        'Round Rock': 'America/Chicago',
        'Clearwater': 'America/New_York',
        'Overland Park': 'America/Chicago',
        'Westminster': 'America/Denver',
        'West Jordan': 'America/Denver',
        'Richmond': 'America/Los_Angeles',
        'Lowell': 'America/New_York',
        'Gresham': 'America/Los_Angeles',
        'Billings': 'America/Denver',
        'San Buenaventura (Ventura)': 'America/Los_Angeles',
        'Pueblo': 'America/Denver',
        'High Point': 'America/New_York',
        'West Covina': 'America/Los_Angeles',
        'Richmond': 'America/New_York',
        'Murrieta': 'America/Los_Angeles',
        'Cambridge': 'America/New_York',
        'Antioch': 'America/Los_Angeles',
        'Temecula': 'America/Los_Angeles',
        'Norwalk': 'America/Los_Angeles',
        'Centennial': 'America/Denver',
        'Everett': 'America/Los_Angeles',
        'Palm Bay': 'America/New_York',
        'Wichita Falls': 'America/Chicago',
        'Green Bay': 'America/Chicago',
        'Daly City': 'America/Los_Angeles',
        'Burbank': 'America/Los_Angeles',
        'Richardson': 'America/Chicago',
        'Pompano Beach': 'America/New_York',
        'North Charleston': 'America/New_York',
        'Broken Arrow': 'America/Chicago',
        'Boulder': 'America/Denver',
        'West Palm Beach': 'America/New_York',
        'Santa Maria': 'America/Los_Angeles',
        'El Monte': 'America/Los_Angeles',
        'Woodbridge': 'America/New_York',
        'Rialto': 'America/Los_Angeles',
        'Las Cruces': 'America/Denver',
        'El Paso': 'America/Denver',
        'Tyler': 'America/Chicago',
        'Lewisville': 'America/Chicago',
        'College Station': 'America/Chicago',
        'San Mateo': 'America/Los_Angeles',
        'Hillsboro': 'America/Los_Angeles',
        'Ventura': 'America/Los_Angeles',
        'Greeley': 'America/Denver',
        'Lansing': 'America/New_York',
        'Inglewood': 'America/Los_Angeles',
        'Rochester': 'America/Chicago',
        'Arvada': 'America/Denver',
        'Miami Gardens': 'America/New_York',
        'Carlsbad': 'America/Los_Angeles',
        'Westminster': 'America/Los_Angeles',
        'Fairfield': 'America/Los_Angeles',
        'Elgin': 'America/Chicago',
        'West Valley City': 'America/Denver',
        'Provo': 'America/Denver',
        'Lakeland': 'America/New_York',
        'Orem': 'America/Denver',
        'Waterbury': 'America/New_York',
        'Charleston': 'America/New_York',
        'Flint': 'America/New_York',
        'Roanoke': 'America/New_York',
        'Fayetteville AR': 'America/Chicago',
        'Allen': 'America/Chicago',
        'Evansville': 'America/Chicago',
        'Odessa': 'America/Chicago',
        'Columbia': 'America/Chicago',
        'Colorado Springs': 'America/Denver',
        'Sterling Heights': 'America/New_York',
        'Cedar Rapids': 'America/Chicago',
        'Coral Springs': 'America/New_York',
        'Clearwater': 'America/New_York',
        'El Cajon': 'America/Los_Angeles',
        'Davenport': 'America/Chicago',
        'Menifee': 'America/Los_Angeles',
        'South Bend': 'America/Indiana/Indianapolis',
        'Lee\'s Summit': 'America/Chicago',
        'Bend': 'America/Los_Angeles',
        'Carmel': 'America/Indiana/Indianapolis',
        'College Station': 'America/Chicago',
        'Edinburg': 'America/Chicago',
        'Sandy': 'America/Denver',
        'Brockton': 'America/New_York',
        'Renton': 'America/Los_Angeles',
        'Tuscaloosa': 'America/Chicago',
        'Bellingham': 'America/Los_Angeles',
        'San Angelo': 'America/Chicago',
        'Pueblo': 'America/Denver',
        'Hemet': 'America/Los_Angeles',
        'Clinton': 'America/Chicago',
        'Kennewick': 'America/Los_Angeles',
        'Longmont': 'America/Denver',
        'Lake Forest': 'America/Los_Angeles',
        'Yakima': 'America/Los_Angeles',
        'Merced': 'America/Los_Angeles',
        'Decatur': 'America/Chicago',
        'Champaign': 'America/Chicago',
        'Kenosha': 'America/Chicago',
        'Chico': 'America/Los_Angeles',
        'Brooklyn Park': 'America/Chicago',
        'Racine': 'America/Chicago',
        'Terre Haute': 'America/Indiana/Indianapolis',
        'Pasco': 'America/Los_Angeles',
        'St. Cloud': 'America/Chicago',
        'Livonia': 'America/New_York',
        'New Bedford': 'America/New_York',
        'Deltona': 'America/New_York',
        'Turlock': 'America/Los_Angeles',
        'Dearborn Heights': 'America/New_York',
        'Lynchburg': 'America/New_York',
        'Bloomington': 'America/Chicago',
        'Loveland': 'America/Denver',
        'Laguna Niguel': 'America/Los_Angeles',
        'Lake Charles': 'America/Chicago',
        'Redwood City': 'America/Los_Angeles',
        'Vineland': 'America/New_York',
        'Erie': 'America/New_York',
        'Pearland': 'America/Chicago',
        'Lower Merion': 'America/New_York',
        'Scranton': 'America/New_York',
        'Hartford': 'America/New_York',
        'Boulder': 'America/Denver',
        'Danbury': 'America/New_York',
        'Toms River': 'America/New_York',
        'Dayton': 'America/New_York',
        'Hamilton': 'America/New_York',
        'Renton': 'America/Los_Angeles',
        'Sunrise': 'America/New_York',
        
        # South America
        'São Paulo': 'America/Sao_Paulo',
        'Buenos Aires': 'America/Argentina/Buenos_Aires',
        'Rio de Janeiro': 'America/Sao_Paulo',
        'Lima': 'America/Lima',
        'Bogotá': 'America/Bogota',
        'Santiago': 'America/Santiago',
        'Caracas': 'America/Caracas',
        'Montevideo': 'America/Montevideo',
        'La Paz': 'America/La_Paz',
        'Quito': 'America/Guayaquil',
        
        # Europe
        'London': 'Europe/London',
        'Paris': 'Europe/Paris',
        'Berlin': 'Europe/Berlin',
        'Rome': 'Europe/Rome',
        'Madrid': 'Europe/Madrid',
        'Amsterdam': 'Europe/Amsterdam',
        'Brussels': 'Europe/Brussels',
        'Vienna': 'Europe/Vienna',
        'Zurich': 'Europe/Zurich',
        'Stockholm': 'Europe/Stockholm',
        'Oslo': 'Europe/Oslo',
        'Copenhagen': 'Europe/Copenhagen',
        'Helsinki': 'Europe/Helsinki',
        'Warsaw': 'Europe/Warsaw',
        'Prague': 'Europe/Prague',
        'Budapest': 'Europe/Budapest',
        'Bucharest': 'Europe/Bucharest',
        'Athens': 'Europe/Athens',
        'Istanbul': 'Europe/Istanbul',
        'Moscow': 'Europe/Moscow',
        'St. Petersburg': 'Europe/Moscow',
        'Kiev': 'Europe/Kiev',
        'Dublin': 'Europe/Dublin',
        'Lisbon': 'Europe/Lisbon',
        'Barcelona': 'Europe/Madrid',
        'Milan': 'Europe/Rome',
        'Frankfurt': 'Europe/Berlin',
        'Munich': 'Europe/Berlin',
        
        # Asia
        'Tokyo': 'Asia/Tokyo',
        'Shanghai': 'Asia/Shanghai',
        'Mumbai': 'Asia/Kolkata',
        'Delhi': 'Asia/Kolkata',
        'Seoul': 'Asia/Seoul',
        'Bangkok': 'Asia/Bangkok',
        'Singapore': 'Asia/Singapore',
        'Hong Kong': 'Asia/Hong_Kong',
        'Dubai': 'Asia/Dubai',
        'Beijing': 'Asia/Shanghai',
        'Manila': 'Asia/Manila',
        'Jakarta': 'Asia/Jakarta',
        'Kuala Lumpur': 'Asia/Kuala_Lumpur',
        'Taipei': 'Asia/Taipei',
        'Ho Chi Minh City': 'Asia/Ho_Chi_Minh',
        'Hanoi': 'Asia/Ho_Chi_Minh',
        'Osaka': 'Asia/Tokyo',
        'Kolkata': 'Asia/Kolkata',
        'Chennai': 'Asia/Kolkata',
        'Bangalore': 'Asia/Kolkata',
        'Karachi': 'Asia/Karachi',
        'Lahore': 'Asia/Karachi',
        'Islamabad': 'Asia/Karachi',
        'Dhaka': 'Asia/Dhaka',
        'Colombo': 'Asia/Colombo',
        'Kathmandu': 'Asia/Kathmandu',
        'Kabul': 'Asia/Kabul',
        'Tehran': 'Asia/Tehran',
        'Baghdad': 'Asia/Baghdad',
        'Riyadh': 'Asia/Riyadh',
        'Kuwait City': 'Asia/Kuwait',
        'Doha': 'Asia/Qatar',
        'Abu Dhabi': 'Asia/Dubai',
        'Muscat': 'Asia/Muscat',
        'Tashkent': 'Asia/Tashkent',
        'Almaty': 'Asia/Almaty',
        'Bishkek': 'Asia/Bishkek',
        'Yerevan': 'Asia/Yerevan',
        'Baku': 'Asia/Baku',
        'Tbilisi': 'Asia/Tbilisi',
        'Jerusalem': 'Asia/Jerusalem',
        'Tel Aviv': 'Asia/Jerusalem',
        'Beirut': 'Asia/Beirut',
        'Damascus': 'Asia/Damascus',
        'Amman': 'Asia/Amman',
        'Nicosia': 'Asia/Nicosia',
        
        # Africa
        'Cairo': 'Africa/Cairo',
        'Lagos': 'Africa/Lagos',
        'Johannesburg': 'Africa/Johannesburg',
        'Cape Town': 'Africa/Johannesburg',
        'Nairobi': 'Africa/Nairobi',
        'Casablanca': 'Africa/Casablanca',
        'Tunis': 'Africa/Tunis',
        'Algiers': 'Africa/Algiers',
        'Addis Ababa': 'Africa/Addis_Ababa',
        'Dar es Salaam': 'Africa/Dar_es_Salaam',
        'Kampala': 'Africa/Kampala',
        'Kigali': 'Africa/Kigali',
        'Lusaka': 'Africa/Lusaka',
        'Harare': 'Africa/Harare',
        'Windhoek': 'Africa/Windhoek',
        'Gaborone': 'Africa/Gaborone',
        'Maputo': 'Africa/Maputo',
        'Antananarivo': 'Indian/Antananarivo',
        'Port Louis': 'Indian/Mauritius',
        'Dakar': 'Africa/Dakar',
        'Abidjan': 'Africa/Abidjan',
        'Accra': 'Africa/Accra',
        'Bamako': 'Africa/Bamako',
        'Ouagadougou': 'Africa/Ouagadougou',
        'Niamey': 'Africa/Niamey',
        'N\'Djamena': 'Africa/Ndjamena',
        'Libreville': 'Africa/Libreville',
        'Kinshasa': 'Africa/Kinshasa',
        'Luanda': 'Africa/Luanda',
        'Douala': 'Africa/Douala',
        'Brazzaville': 'Africa/Brazzaville',
        'Bangui': 'Africa/Bangui',
        'Malabo': 'Africa/Malabo',
        'Khartoum': 'Africa/Khartoum',
        'Djibouti': 'Africa/Djibouti',
        'Asmara': 'Africa/Asmara',
        'Mogadishu': 'Africa/Mogadishu',
        
        # Oceania
        'Sydney': 'Australia/Sydney',
        'Melbourne': 'Australia/Melbourne',
        'Brisbane': 'Australia/Brisbane',
        'Perth': 'Australia/Perth',
        'Adelaide': 'Australia/Adelaide',
        'Darwin': 'Australia/Darwin',
        'Hobart': 'Australia/Hobart',
        'Canberra': 'Australia/Sydney',
        'Auckland': 'Pacific/Auckland',
        'Wellington': 'Pacific/Auckland',
        'Christchurch': 'Pacific/Auckland',
        'Suva': 'Pacific/Fiji',
        'Port Moresby': 'Pacific/Port_Moresby',
        'Noumea': 'Pacific/Noumea',
        'Papeete': 'Pacific/Tahiti',
        'Apia': 'Pacific/Apia',
        'Nuku\'alofa': 'Pacific/Tongatapu',
        'Port Vila': 'Pacific/Efate',
        'Honiara': 'Pacific/Guadalcanal',
        'Majuro': 'Pacific/Majuro',
        'Tarawa': 'Pacific/Tarawa',
        'Funafuti': 'Pacific/Funafuti',
        'Nuku\'alofa': 'Pacific/Tongatapu',
        
        # Caribbean
        'Havana': 'America/Havana',
        'Kingston': 'America/Jamaica',
        'Santo Domingo': 'America/Santo_Domingo',
        'Port-au-Prince': 'America/Port-au-Prince',
        'San Juan': 'America/Puerto_Rico',
        'Bridgetown': 'America/Barbados',
        'Port of Spain': 'America/Port_of_Spain',
        
        # Central America
        'Guatemala City': 'America/Guatemala',
        'Belize City': 'America/Belize',
        'Tegucigalpa': 'America/Tegucigalpa',
        'Managua': 'America/Managua',
        'San José': 'America/Costa_Rica',
        'Panama City': 'America/Panama',
        
        # UTC Reference
        'UTC': 'UTC'
    }

    selected = ['New York', 'London', 'Sydney']

    if request.method == 'POST':
        selected = [
            request.form.get('city1'),
            request.form.get('city2'),
            request.form.get('city3')
        ]

    times = {}
    for city in selected:
        tz = available_cities.get(city, 'UTC')
        tz_time = datetime.now(pytz.timezone(tz)).strftime("%Y-%m-%d %H:%M:%S")
        times[city] = tz_time

    return render_template(
        'world_clock.html',
        times=times,
        cities=available_cities.keys(),
        selected=selected
    )

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)